import type { SampleSnapshot } from "./types";

/** Fictional Northfield Manufacturing day-shift snapshot. Sample data only. */
export const sampleSnapshot: SampleSnapshot = {
  plant: {
    scenarioId: "northfield_day_shift",
    name: "Northfield Manufacturing",
    shift: "Day",
    workCenters: [
      "CNC Machining",
      "Assembly Line 1",
      "Assembly Line 2",
      "Packaging Line",
      "Injection Molding",
    ],
  },
  production: [
    {
      id: "prod-cnc",
      workCenter: "CNC Machining",
      productFamily: "Machined Shaft Assembly",
      scheduledQty: 420,
      actualQty: 428,
      scheduledHours: 8,
      actualHours: 8,
      downtimeMinutes: 8,
      previousDowntimeMinutes: 41,
      previousAttainmentPct: 94,
      primaryDowntimeReason: "Planned tool change",
      recoveryNote: "No recovery required.",
      recommendedAction: "Hold the current sequence. No leadership action required.",
    },
    {
      id: "prod-asm1",
      workCenter: "Assembly Line 1",
      productFamily: "Fastener Kit",
      scheduledQty: 1200,
      actualQty: 1170,
      scheduledHours: 8,
      actualHours: 7.6,
      downtimeMinutes: 22,
      previousDowntimeMinutes: 14,
      previousAttainmentPct: 99,
      primaryDowntimeReason: "Waiting on stainless fastener kit",
      recoveryNote: "30 units below plan.",
      recommendedAction:
        "Protect remaining Fastener Kit demand if the fastener replenishment slips.",
    },
    {
      id: "prod-asm2",
      workCenter: "Assembly Line 2",
      productFamily: "Machined Shaft Assembly",
      scheduledQty: 1000,
      actualQty: 860,
      scheduledHours: 8,
      actualHours: 7,
      downtimeMinutes: 62,
      previousDowntimeMinutes: 11,
      previousAttainmentPct: 98,
      primaryDowntimeReason: "Conveyor drive fault",
      recoveryNote: "140 units below plan.",
      recommendedAction:
        "Confirm the temporary repair holds and agree a recovery plan before second shift.",
    },
    {
      id: "prod-pack",
      workCenter: "Packaging Line",
      productFamily: "Packaging Set",
      scheduledQty: 1800,
      actualQty: 1845,
      scheduledHours: 8,
      actualHours: 7.8,
      downtimeMinutes: 12,
      previousDowntimeMinutes: 47,
      previousAttainmentPct: 97,
      primaryDowntimeReason: "Planned changeover",
      recoveryNote: "No recovery required.",
      recommendedAction: "Keep the current packaging sequence.",
    },
    {
      id: "prod-mold",
      workCenter: "Injection Molding",
      productFamily: "Molded Housing",
      scheduledQty: 520,
      actualQty: 498,
      scheduledHours: 8,
      actualHours: 7.4,
      downtimeMinutes: 36,
      previousDowntimeMinutes: 18,
      previousAttainmentPct: 101,
      primaryDowntimeReason: "Quality hold for surface-finish inspection",
      recoveryNote: "22 units below plan.",
      recommendedAction:
        "Keep 100% inspection in place until Quality releases the process.",
    },
  ],
  quality: [
    {
      id: "qty-housing-finish",
      workCenter: "Injection Molding",
      productFamily: "Molded Housing",
      issue: "Molded Housing — Surface Finish",
      defectCategory: "Surface finish",
      quantityAffected: 96,
      scrapQty: 18,
      reworkQty: 78,
      inspectedQty: 429,
      previousScrapPct: 1.4,
      alertStatus: "active",
      containmentStatus: "active",
      owner: "Quality",
      immediateAction:
        "Maintain 100% visual inspection until root cause is confirmed.",
      structuralAction: "Review mold condition and process parameters.",
    },
  ],
  supply: [
    {
      id: "sup-fastener",
      item: "Stainless Fastener Kit",
      supplier: "Northstar Fasteners",
      daysOfSupply: 2.8,
      previousDaysOfSupply: 5.2,
      replenishmentDays: 4,
      affectedWorkCenter: "Assembly Line 1",
      owner: "Buyer",
      immediateAction:
        "Confirm shipment and evaluate available internal inventory.",
      structuralAction:
        "Review lead-time assumptions and second-source capability.",
    },
    {
      id: "sup-resin",
      item: "Housing Polymer Resin",
      supplier: "Lakeside Polymers",
      daysOfSupply: 3.6,
      previousDaysOfSupply: 4.1,
      replenishmentDays: 6,
      affectedWorkCenter: "Injection Molding",
      owner: "Supply Chain",
      immediateAction:
        "Confirm the open resin release and keep molding on the current lot.",
      structuralAction:
        "Review safety-stock policy for the housing resin family.",
    },
  ],
  maintenance: [
    {
      id: "mnt-conveyor",
      asset: "Assembly Line 2 Conveyor Drive",
      workCenter: "Assembly Line 2",
      issue: "Unplanned conveyor drive fault",
      downtimeMinutes: 62,
      temporaryCountermeasure: "Temporary repair completed",
      permanentActionStatus: "Scheduled after second shift",
      owner: "Maintenance",
      immediateAction:
        "Verify the repair holds through the current production run.",
      structuralAction:
        "Replace the worn drive component and review the PM interval.",
    },
  ],
  schedule: [
    {
      id: "sch-bearing",
      productFamily: "Bearing Assembly",
      finishedGoodsDays: 1.4,
      openDemand: 640,
      nextShipment: "Tomorrow",
      shipmentInDays: 1,
    },
    {
      id: "sch-shaft",
      productFamily: "Machined Shaft Assembly",
      finishedGoodsDays: 1.8,
      openDemand: 920,
      nextShipment: "In 2 days",
      shipmentInDays: 2,
    },
    {
      id: "sch-fastener-kit",
      productFamily: "Fastener Kit",
      finishedGoodsDays: 2.1,
      openDemand: 1100,
      nextShipment: "In 3 days",
      shipmentInDays: 3,
    },
    {
      id: "sch-housing",
      productFamily: "Molded Housing",
      finishedGoodsDays: 2.6,
      openDemand: 480,
      nextShipment: "In 4 days",
      shipmentInDays: 4,
    },
    {
      id: "sch-bracket",
      productFamily: "Aluminum Bracket",
      finishedGoodsDays: 3.2,
      openDemand: 360,
      nextShipment: "In 5 days",
      shipmentInDays: 5,
    },
    {
      id: "sch-packaging",
      productFamily: "Packaging Set",
      finishedGoodsDays: 2.8,
      openDemand: 1500,
      nextShipment: "Tomorrow",
      shipmentInDays: 1,
    },
  ],
};

export function getSampleSnapshot(): SampleSnapshot {
  return sampleSnapshot;
}
