import { toCsv } from "@/lib/signal/csv";
import { addDays } from "@/lib/signal/dates";
import type { RawPoRow } from "@/lib/signal/types";

export const SAMPLE_CSV_HEADERS = [
  "po_number",
  "supplier",
  "item",
  "description",
  "order_date",
  "due_date",
  "promised_date",
  "quantity_ordered",
  "quantity_received",
  "buyer",
  "inventory_on_hand",
  "daily_usage",
  "lead_time_days",
  "unit_cost",
] as const;

type SampleSpec = {
  poNumber: string;
  supplier: string;
  item: string;
  description: string;
  orderOffset: number;
  dueOffset: number;
  promisedOffset: number | null;
  quantityOrdered: number;
  quantityReceived: number;
  buyer: string;
  inventoryOnHand?: number;
  dailyUsage?: number;
  leadTimeDays?: number;
  unitCost: number;
};

const SAMPLE_SPECS: SampleSpec[] = [
  {
    poNumber: "450218",
    supplier: "Apex Machining",
    item: "MS-240",
    description: "Machined Shaft",
    orderOffset: -45,
    dueOffset: -10,
    promisedOffset: -8,
    quantityOrdered: 240,
    quantityReceived: 0,
    buyer: "J. Chen",
    inventoryOnHand: 48,
    dailyUsage: 8,
    leadTimeDays: 21,
    unitCost: 52,
  },
  {
    poNumber: "450441",
    supplier: "Harbor Plastics",
    item: "PH-18",
    description: "Injection-Molded Housing",
    orderOffset: -20,
    dueOffset: 18,
    promisedOffset: 18,
    quantityOrdered: 80,
    quantityReceived: 0,
    buyer: "M. Alvarez",
    inventoryOnHand: 120,
    dailyUsage: 20,
    leadTimeDays: 28,
    unitCost: 142.5,
  },
  {
    poNumber: "450106",
    supplier: "Ridgeway Metals",
    item: "ST-50",
    description: "Steel Tubing",
    orderOffset: -60,
    dueOffset: -14,
    promisedOffset: -12,
    quantityOrdered: 50,
    quantityReceived: 0,
    buyer: "R. Patel",
    leadTimeDays: 35,
    unitCost: 248,
  },
  {
    poNumber: "450502",
    supplier: "Keystone Components",
    item: "BR-200",
    description: "Bearings",
    orderOffset: -40,
    dueOffset: -4,
    promisedOffset: -3,
    quantityOrdered: 200,
    quantityReceived: 0,
    buyer: "J. Chen",
    leadTimeDays: 21,
    unitCost: 14.25,
  },
  {
    poNumber: "450518",
    supplier: "Keystone Components",
    item: "RG-80",
    description: "Rubber Gaskets",
    orderOffset: -28,
    dueOffset: -2,
    promisedOffset: -1,
    quantityOrdered: 80,
    quantityReceived: 30,
    buyer: "J. Chen",
    unitCost: 3.8,
  },
  {
    poNumber: "450533",
    supplier: "Keystone Components",
    item: "EC-500",
    description: "Electrical Connectors",
    orderOffset: -25,
    dueOffset: 2,
    promisedOffset: 2,
    quantityOrdered: 500,
    quantityReceived: 0,
    buyer: "K. Brooks",
    unitCost: 1.15,
  },
  {
    poNumber: "450620",
    supplier: "Atlas Industrial",
    item: "AB-40",
    description: "Aluminum Bracket",
    orderOffset: -30,
    dueOffset: 3,
    promisedOffset: 3,
    quantityOrdered: 40,
    quantityReceived: 4,
    buyer: "M. Alvarez",
    leadTimeDays: 14,
    unitCost: 86,
  },
  {
    poNumber: "450712",
    supplier: "Delta Foam",
    item: "PF-120",
    description: "Protective Foam Inserts",
    orderOffset: -22,
    dueOffset: 3,
    promisedOffset: 3,
    quantityOrdered: 120,
    quantityReceived: 20,
    buyer: "M. Alvarez",
    inventoryOnHand: 70,
    dailyUsage: 10,
    unitCost: 2.4,
  },
  {
    poNumber: "450801",
    supplier: "Apex Machining",
    item: "FC-20",
    description: "Finished Collar",
    orderOffset: -18,
    dueOffset: 5,
    promisedOffset: null,
    quantityOrdered: 20,
    quantityReceived: 0,
    buyer: "J. Chen",
    leadTimeDays: 21,
    unitCost: 38.5,
  },
  {
    poNumber: "450818",
    supplier: "Apex Machining",
    item: "FB-15",
    description: "Flanged Bushing",
    orderOffset: -16,
    dueOffset: 12,
    promisedOffset: null,
    quantityOrdered: 15,
    quantityReceived: 0,
    buyer: "K. Brooks",
    unitCost: 44,
  },
  {
    poNumber: "450901",
    supplier: "Summit Packaging",
    item: "CT-12",
    description: "Corrugated Cartons",
    orderOffset: -21,
    dueOffset: 9,
    promisedOffset: null,
    quantityOrdered: 500,
    quantityReceived: 0,
    buyer: "R. Patel",
    unitCost: 1.85,
  },
  {
    poNumber: "450918",
    supplier: "Summit Packaging",
    item: "CT-16",
    description: "Corrugated Cartons",
    orderOffset: -21,
    dueOffset: 14,
    promisedOffset: null,
    quantityOrdered: 400,
    quantityReceived: 0,
    buyer: "R. Patel",
    unitCost: 2.1,
  },
  {
    poNumber: "450930",
    supplier: "Summit Packaging",
    item: "LB-250",
    description: "Shipping Labels",
    orderOffset: -14,
    dueOffset: 6,
    promisedOffset: null,
    quantityOrdered: 250,
    quantityReceived: 0,
    buyer: "R. Patel",
    unitCost: 0.42,
  },
  {
    poNumber: "450944",
    supplier: "Summit Packaging",
    item: "PL-60",
    description: "Pallet Labels",
    orderOffset: -10,
    dueOffset: 21,
    promisedOffset: null,
    quantityOrdered: 60,
    quantityReceived: 0,
    buyer: "K. Brooks",
    unitCost: 1.15,
  },
  {
    poNumber: "451002",
    supplier: "Harbor Plastics",
    item: "CH-8",
    description: "Molded Cap Housing",
    orderOffset: -12,
    dueOffset: 10,
    promisedOffset: null,
    quantityOrdered: 80,
    quantityReceived: 0,
    buyer: "M. Alvarez",
    unitCost: 6.75,
  },
  {
    poNumber: "451101",
    supplier: "Ridgeway Metals",
    item: "AL-12",
    description: "Aluminum Bracket",
    orderOffset: -15,
    dueOffset: 24,
    promisedOffset: 24,
    quantityOrdered: 12,
    quantityReceived: 0,
    buyer: "R. Patel",
    leadTimeDays: 28,
    unitCost: 64,
  },
  {
    poNumber: "451214",
    supplier: "Apex Machining",
    item: "MS-110",
    description: "Machined Shaft",
    orderOffset: -20,
    dueOffset: 30,
    promisedOffset: 30,
    quantityOrdered: 20,
    quantityReceived: 14,
    buyer: "J. Chen",
    unitCost: 52,
  },
  {
    poNumber: "451222",
    supplier: "Keystone Components",
    item: "BR-40",
    description: "Bearings",
    orderOffset: -18,
    dueOffset: 16,
    promisedOffset: 16,
    quantityOrdered: 40,
    quantityReceived: 0,
    buyer: "J. Chen",
    unitCost: 14.25,
  },
  {
    poNumber: "451330",
    supplier: "Atlas Industrial",
    item: "AB-90",
    description: "Aluminum Bracket",
    orderOffset: -8,
    dueOffset: 28,
    promisedOffset: 28,
    quantityOrdered: 30,
    quantityReceived: 0,
    buyer: "M. Alvarez",
    inventoryOnHand: 400,
    dailyUsage: 10,
    unitCost: 86,
  },
  {
    poNumber: "451341",
    supplier: "Summit Packaging",
    item: "CT-24",
    description: "Corrugated Cartons",
    orderOffset: -6,
    dueOffset: 35,
    promisedOffset: 35,
    quantityOrdered: 200,
    quantityReceived: 0,
    buyer: "R. Patel",
    unitCost: 2.45,
  },
  {
    poNumber: "451355",
    supplier: "Northstar Fasteners",
    item: "FK-600",
    description: "Stainless Fastener Kit",
    orderOffset: -25,
    dueOffset: 19,
    promisedOffset: 19,
    quantityOrdered: 60,
    quantityReceived: 40,
    buyer: "M. Alvarez",
    unitCost: 8.4,
  },
  {
    poNumber: "451362",
    supplier: "Ridgeway Metals",
    item: "ST-80",
    description: "Steel Tubing",
    orderOffset: -12,
    dueOffset: 45,
    promisedOffset: 45,
    quantityOrdered: 8,
    quantityReceived: 0,
    buyer: "K. Brooks",
    unitCost: 248,
  },
  {
    poNumber: "451370",
    supplier: "Harbor Plastics",
    item: "PH-22",
    description: "Injection-Molded Housing",
    orderOffset: -14,
    dueOffset: 22,
    promisedOffset: 22,
    quantityOrdered: 10,
    quantityReceived: 0,
    buyer: "J. Chen",
    unitCost: 142.5,
  },
  {
    poNumber: "451388",
    supplier: "Northstar Fasteners",
    item: "FK-120",
    description: "Stainless Fastener Kit",
    orderOffset: -11,
    dueOffset: 14,
    promisedOffset: 14,
    quantityOrdered: 15,
    quantityReceived: 0,
    buyer: "K. Brooks",
    unitCost: 8.4,
  },
  {
    poNumber: "449100",
    supplier: "Apex Machining",
    item: "MS-010",
    description: "Machined Shaft",
    orderOffset: -50,
    dueOffset: -5,
    promisedOffset: -6,
    quantityOrdered: 12,
    quantityReceived: 12,
    buyer: "J. Chen",
    unitCost: 52,
  },
  {
    poNumber: "449112",
    supplier: "Summit Packaging",
    item: "CT-04",
    description: "Corrugated Cartons",
    orderOffset: -40,
    dueOffset: -2,
    promisedOffset: -3,
    quantityOrdered: 80,
    quantityReceived: 80,
    buyer: "R. Patel",
    unitCost: 1.85,
  },
  {
    poNumber: "449124",
    supplier: "Northstar Fasteners",
    item: "FK-010",
    description: "Stainless Fastener Kit",
    orderOffset: -30,
    dueOffset: 1,
    promisedOffset: 0,
    quantityOrdered: 2,
    quantityReceived: 2,
    buyer: "K. Brooks",
    unitCost: 8.4,
  },
];

function specToRow(spec: SampleSpec, asOfDate: string): RawPoRow {
  return {
    poNumber: spec.poNumber,
    supplier: spec.supplier,
    item: spec.item,
    description: spec.description,
    orderDate: addDays(asOfDate, spec.orderOffset),
    dueDate: addDays(asOfDate, spec.dueOffset),
    promisedDate:
      spec.promisedOffset === null
        ? null
        : addDays(asOfDate, spec.promisedOffset),
    quantityOrdered: spec.quantityOrdered,
    quantityReceived: spec.quantityReceived,
    buyer: spec.buyer,
    inventoryOnHand: spec.inventoryOnHand ?? null,
    dailyUsage: spec.dailyUsage ?? null,
    leadTimeDays: spec.leadTimeDays ?? null,
    unitCost: spec.unitCost,
  };
}

export function buildSampleRows(asOfDate: string): RawPoRow[] {
  return SAMPLE_SPECS.map((spec) => specToRow(spec, asOfDate));
}

export function buildSampleCsv(asOfDate: string): string {
  const rows = buildSampleRows(asOfDate).map((row) => [
    row.poNumber,
    row.supplier,
    row.item,
    row.description,
    row.orderDate,
    row.dueDate,
    row.promisedDate,
    row.quantityOrdered,
    row.quantityReceived,
    row.buyer,
    row.inventoryOnHand,
    row.dailyUsage,
    row.leadTimeDays,
    row.unitCost,
  ]);

  return toCsv([...SAMPLE_CSV_HEADERS], rows);
}
